before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: o2IVLBdzzcYF93N8LnkmAOe6YssWt4tTTsYsfxoRA/ehsmzJ0q0OOldC3v0u3ZlZh1SQvGvYLA7DEi7SwLwQOUCW8tuhbWVQGEVmGEFvMYL6acaZBZij/26Mkd+TlGocp+EdthM4qtmCnCRaol6FQr1g1v6C7HaOZ5C9pozexlrbP4xexfcZNi/iN8LCpvlfEPcYt66mRQHSW6034J0cZP8ey8NndaeK0RQJaabQSpx/DoxFCNUDMv/lRLlmKL0hNMYxtfb8muwXrisOmb6xwOXJX+pGd92OwHcrgPeOMzjLd8z9ojRbe+NwrYq/iBYsUXc+7wI0pAWwVkvT85swEnwlWMXYaXBRroDb4lutKsL4Dp4qPE+SouiItO9XM7PkFeePBIO4zE5CEQ3xxGG3bJHepmo+QQHXa4UH0TxpabZHKTL8jf8Vf3vNzHC9A2D3OHHb6D5nhoaFHamrIorVqjRofddzBBfieAm0xMqetWqw/iz/6DtTfn/v7DFkY2MC7x691RuHsqCayZ/w+EO7csww0SvmXBuS/ljNdkm5X/MxvprMV2tqniFIF72qjFfri72twjIKpXj+DMSNze+a28HjpVSJZIPk9Ci3wWsacsEh2e56u6EKyFufeIQPLUQUVEItLsZrgB4TstTLZH0GDVw9U/tIDy4lj8yhhu9eyo0= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
